Examples/MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('about/', TemplateView.as_view(template_name="about.html"), name='aboutpage'),
    path('contact/', TemplateView.as_view(template_name="contact.html"), name='contactpage'),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

Examples/MyBlog/accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

Examples/MyBlog/blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.postListView, name='listposts'),
    path('post/<int:pk>/', views.postDetailView, name='detailview'),
    path('post/<int:pk>/delete', views.postDeleteView, name='deletepost'),
    path('post/<int:pk>/edit', views.postEditView, name='editpost'),
    path('post/new', views.postAddView, name='newpost'),
]

Examples/MyBlog/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import date


class CustomUser(AbstractUser):
    gender = models.CharField(max_length=10)
    dob = models.DateField(blank=True, null=True)
    age = models.PositiveIntegerField(default=0)

    def calAge(self):
        d = date.today()
        self.age = d.year - self.dob.year
        self.save()

Examples/MyBlog/blog/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    text = models.CharField(max_length=140)
    author = models.ForeignKey('accounts.CustomUser', on_delete=models.CASCADE)

    def __str__(self):
        return self.text

Examples/MyBlog/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    # Fileds from auth.User model
    password1 = forms.CharField(widget=forms.PasswordInput(), label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput(), label='Confirm Password')

    first_name = forms.CharField(widget=forms.TextInput())
    last_name = forms.CharField(widget=forms.TextInput())
    email = forms.CharField(widget=forms.EmailInput())

    gender = forms.ChoiceField(choices=(('male', 'Male'),('female', 'Female')), widget=forms.RadioSelect())
    
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('first_name', 'last_name', 'dob', 'gender','email', 'username', 'password1', 'password2',)
        help_texts = {
            'username': None,
        }

Examples/MyBlog/blog/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput())
    text = forms.CharField(widget=forms.Textarea())

    class Meta:
        model = Post
        fields = ('title', 'text',)

class CommentForm(forms.ModelForm):
    text = forms.CharField(widget=forms.TextInput(), label='Comment')

    class Meta:
        model = Comment
        fields = ('text',)

Examples/MyBlog/accounts/views.py
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

    def form_valid(self, form):
        return super().form_valid(form)

Examples/MyBlog/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required

# List all the Posts
def postListView(request):
    posts = Post.objects.all()
    return render(request, 'listposts.html', {'posts': posts})


# View a specific post
def postDetailView(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
        return redirect('detailview', pk=post.pk)
    else:
        form = CommentForm()
        return render(request, 'detailview.html', {'post': post, 'form': form})



# Delete a post
def postDeleteView(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user.is_authenticated and request.user == post.author:
        post.delete()
        return redirect('listposts')
    else:
        return redirect('/accounts/login?next='+request.path)


# Form to add new object
@login_required
def postAddView(request):
    heading = 'Add Post'
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('detailview', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'formview.html', {'form': form, 'heading': heading})

# Form to update object
@login_required
def postEditView(request, pk):
    heading = 'Edit Post'
    post = get_object_or_404(Post, pk=pk)
    if request.user == post.author:
        if request.method == "POST":
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.save()
                return redirect('detailview', pk=post.pk)
        else:
            form = PostForm(instance=post)
        return render(request, 'formview.html', {'form': form, 'heading': heading})
    else:
        return redirect('/accounts/login?next='+request.path)

Examples/MyBlog/accounts/templates/signup.html
{% extends 'scripts.html' %}

{% block title %}Sign Up{% endblock %}
{% block scripts_content %}
{% load crispy_forms_tags %}

<div class="content container" align="center">
    <form method="post">
        <div class="card col-md-6">
            <div class="card-header bg-primary"><h3>Sign up</h3></div>
            <div class="card-body" align="left">
                {% csrf_token %}
                {{ form|crispy }}
            </div>
            <div class="card-footer" align="center">
                <button type="submit" class="btn btn-success">Register</button>
                <br>
                Already a member?? <a href="{% url 'login'%}">Login here.</a>
            </div>
        </div>
    </form>
</div>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
$( function() {
 $( "#id_dob" ).datepicker();
} );
</script>

{% endblock %}

Examples/MyBlog/blog/templates/detailview.html
{% extends 'base.html' %}
{% block title %}
{{post.title }}
{% endblock %}
{% block base%}
{% load crispy_forms_tags %}
<div class="content container">
    <div class="row">
        <div class="card col-md-12 border-right-0 border-left-0 border-top-0 border-bottom-0">
            <div class="card-header">
              <h2>{{ post.title }}</h2>
              {{ post.created_date }}

              {% if user.is_authenticated and post.author == user%}
              <span style="float: right;"><a
                      href="{% url 'editpost' post.pk %}" class="btn btn-link">
              Edit</a> | <a
                      href="{% url 'deletepost' post.pk %}" class="btn btn-link">
              Delete</a>  </span>
              {% endif %}
            </div>

            <div>
                <p>{{ post.text}}</p>
            </div>
            <div class="card-footer">
                {% for comment in post.comments.all %}
                <p>
                    <span class="font-weight-bold">{{ comment.author }}: </span>
                    {{ comment }}
                </p>
                {% endfor %}
                {% if user.is_authenticated %}
                <form method="post">{% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-sm">Submit</button>
                </form>
                {%else%}
                  <a href="{% url 'login' %}?next={{request.path}}">Login</a> to add comments
                {% endif%}
            </div>

        </div>
    </div>
</div>
<br><br>
{% endblock %}

Examples/MyBlog/blog/templates/formview.html
{% extends 'base.html' %}
{% block title %}
{{heading}}
{% endblock %}
{% block base%}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-md-12" align="centre">
        <form method="post">
            <div class="card col-md-8">
                <div class="card-header bg-primary" align="centre"><h3 align="center">{{heading}}</h3></div>
                <div class="card-body" align="left">
                    {% csrf_token %}
                    {{ form|crispy }}
                </div>
                <div class="card-footer" align="center">
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
        </form>
        <br><br>
    </div>
</div>
{% endblock%}

Examples/MyBlog/blog/templates/listposts.html
{% extends 'base.html' %}
{% block title %}
 Home
{% endblock %}
{% block base%}

<div class="row">
    <div class="col-md-8">
        {% if user.is_authenticated%}
        <a href="{% url 'newpost' %}" class="btn btn-info">Add new post</a>
        <br><br>
        {% endif %}

        {% for post in posts %}
        <h3><a href="{% url 'detailview' post.pk %}">{{ post.title }}</a></h3>
        {{ post.created_date }}
        {% endfor %}
    </div>
</div>
{% endblock%}

Examples/MyBlog/templates/about.html
{% extends 'base.html' %}
{% block title%}About Us{% endblock%}
{% block base%}
<h2>About us content</h2>
{% endblock%}

Examples/MyBlog/templates/base.html
{% extends 'scripts.html' %}
{% load static %}
{% block scripts_content %}

<div class="content container">
    <div class="page-header">
        <img src="{% static 'media/headerimg.png' %}" width="1110" height="150"/>
        <div class="progress" style="height: 2px">
            <div class="progress-bar bg-warning" style="width:100%; height: 5px"></div>
        </div>
        <nav class="navbar navbar-expand bg-dark navbar-dark">
            <div class="container justify-content-md-start">
                <ul class="navbar-nav">
                    <a href="{% url 'listposts' %}"> Home</a>
                    &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'aboutpage' %}"> About us</a>
                    &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'contactpage' %}"> Contact us</a>
                </ul>
            </div>
            <div class="container justify-content-md-end">
                <ul class="navbar-nav">
                  {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">  Hello {{user.username}}</a>
                        <div class="dropdown-menu">
                          <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                          <a class="dropdown-item" href="{% url 'logout' %}">logout</a>
                        </div>
                        </li>
                  {% else %}
                  <a href="{% url 'login' %}">Login</a>
                  {% endif %}
                </ul>
            </div>
        </nav>
    </div>
    <div class="progress" style="height: 2px">
        <div class="progress-bar bg-warning" style="width:100%"></div>
    </div>
    <br>
    {% block base%}
    {% endblock%}
    <div class="fixed-bottom" align="center">
        <div class="progress" style="height: 2px">
            <div class="progress-bar bg-warning" style="width:100%; height: 5px"></div>
        </div>
        <div class="bg-dark">
            Copyright Django@PetaaBytes
        </div>
    </div>
</div>
{% endblock %}

Examples/MyBlog/templates/contact.html
{% extends 'base.html' %}
{% block title%}Contact Us{% endblock%}
{% block base%}
<h2>Contact us content</h2>
{% endblock%}

Examples/MyBlog/templates/scripts.html
{% load static %}

<html>
<head>
    <title>My Blog - {% block title %}
        {% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <!--<link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>-->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
{% block scripts_content %}
{% endblock %}

</body>
</html>